### ISSUE TITLE
RSS feeds issue customers having issues with iTunes and Social feeds

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#101]
A customer reached out to Hootsuite referring to the social feeds and this is what they said: 
While the RSS feed <http://lighthousehamilton.ca/sermons/feed> is valid, it does appear to have a major flaw that is causing inconsistent publishing. Feeds should not be served with the "text/html" media type.

You can view the error here on the RSS Validator - http://www.rssboard.org/rss-validator/check.cgi?url=http%3A%2F%2Fwww.lighthousehamilton.ca%2Fsermons%2Ffeed%2F

In order to have a consistent publishing experience, we recommend that this flaw with the feed be corrected.

Is this something we can fix?
Here's customer thread:  https://secure.helpscout.net/conversation/67219923/3147/

Here's admin:
In case you need to take a look: http://www.lighthousehamilton.ca/
Username: churchthemes
Password: uplifted1

**Comment by angela-crist** [comment]
@chriswallace Can you take a look at this today?

**Comment by chriswallace** [comment]
This is an issue with their web server. It is not serving RSS feeds as the correct content type. If you run our feed through the validator, it does not have the same error. My recommendation would be to ask the webhost to fix the issue and serve xml content using the proper mime type. http://www.rssboard.org/rss-validator/check.cgi?url=http%3A%2F%2Fdemo.churchthemes.net%2Fuplifted%2Fsermons%2Ffeed%2F

**Comment by chriswallace** [comment]
Closing because it is not a theme bug, but feel free to communicate on this thread as needed.
