### ISSUE TITLE
Customer has white text in a white text box 

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#103]
Customer site:  http://narrative.church/

This occurs on this pages:  It is the search bar widget in the footer and information bars on the 'Connect' page.

What I've done so far:
- Changes their customer colors to see if any where creating this
- Changed the colors back nothing changed that
- Deactivated plugins one at a time (all are reactivated) 

Admin:
User Name: tdoering
Password: Red45@ctober

Customer thread:  https://secure.helpscout.net/conversation/81544334/3952/
Chris suggested:  https://liftux.slack.com/archives/faithmade/p1428518212000083

![screen shot 2015-04-08 at 2 40 57 pm](https://cloud.githubusercontent.com/assets/7047954/7052556/54ec73ca-ddfd-11e4-8e28-6dde3183f248.png)

**Comment by garand** [comment]
This isn't difficult. I'll have it done on Wednesday.

**Comment by angela-crist** [comment]
@garand Any chance you could do this today?  The customer has been waiting since 4/8.  Let me know if not I will just update him with Wednesday.  Thanks!

**Comment by garand** [comment]
I may be able to get to it later, but no promises.

**Comment by angela-crist** [comment]
Saw you talking to Chris about this any updates? Plan of action?

**Comment by garand** [comment]
I've not heard back from @chriswallace. I'll put in a temporary fix until we can assess further.

**Comment by angela-crist** [comment]
Awesome @garand thanks for the update! Let me know when the temp fix is ready to show the customer.

**Comment by garand** [comment]
This is fixed and deployed. Theme version 1.2.2. I also updated this customer's site and confirmed the change.

**Comment by angela-crist** [comment]
Yea!!! Thanks @garand Looks great!
