### ISSUE TITLE
Customer issue: Save PDF and save audio not working within sermons

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#104]
This customer has a multi-site and I don't know if this is part of the problem.
With a multi-site I was unsure where to find the plugins to take a look if we would want to suggest deactivating.

http://www.denverchurchofchrist.org/
user: support
pass: support#123

Here are some of the links to the sermons:
http://www.denverchurchofchrist.org/sermons/a-few-good-men-and-women-hans-rasmussen/

http://www.denverchurchofchrist.org/sermons/good-enough-parenting-lesson-5-frank-erica-kim/

http://www.denverchurchofchrist.org/sermons/give-to-thrive/

When you click on one Save PDF of Save Audio it just takes you to homepage, the link looks like this:  http://www.denverchurchofchrist.org/?download=%2F2015%2F03%2F20150308_sermon.mp3

Customer thread:  https://secure.helpscout.net/conversation/81526127/3951/

**Comment by garand** [comment]
I'll review this on Wednesday.

**Comment by angela-crist** [comment]
@garand I logged into their site and have requested them to update the latest version of the theme.  Hold off on this until we see this issue in the updated version.

Thanks!

**Comment by angela-crist** [comment]
I haven't heard back from customer, so closing for now
