### ISSUE TITLE
Updating theme results in download fail

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#113]
![screen shot 2015-04-16 at 11 35 38 am](https://cloud.githubusercontent.com/assets/7047954/7185283/c38d9128-e42f-11e4-99e2-8d067d3ff261.png)

this happened after #103 not sure if related but Anthony took a look and wasn't sure what it could be. You can see conversation here:  https://liftux.slack.com/archives/upthemes/p1429198787000813

This is the customer site I was working with:
Refreshingwaterslv.org
Username support
Pass 1SupportHelp

**Comment by angela-crist** [comment]
This customer is using another page for the homepage other than the homepage template.  When I tested I used the page Home using the homepage.  For now I placed it back to what the customer had.

**Comment by chriswallace** [comment]
Just ran the update from their site and it worked for me. May have been related to the hosting switchover.
