### ISSUE TITLE
Warnings when in customizer on customer site

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#114]
![screen shot 2015-04-16 at 12 02 18 pm](https://cloud.githubusercontent.com/assets/7047954/7185416/77716ef8-e430-11e4-8de1-46c243d5268b.png)

Talked with Anthony but he wasn't sure and said to assign to you. 

Refreshingwaterslv.org
Username support
Pass 1SupportHelp

**Comment by angela-crist** [comment]
This customer is using another page for the homepage other than the homepage template.  When I tested I used the page Home using the homepage.  For now I placed it back to what the customer had.

**Comment by chriswallace** [comment]
Can this be closed then? It looks like their host is not recognizing the __DIR__ constant in PHP. Please have them update their PHP version to 5.2.4 or higher.

**Comment by angela-crist** [comment]
Informed customer
