### ISSUE TITLE
Dropdown menus no longer work on ChurchThemes version including Mobile

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#116]
![screen shot 2015-04-28 at 4 47 58 pm](https://cloud.githubusercontent.com/assets/7047954/7379935/605f96be-edc6-11e4-9aa2-d4eef34aa532.png)

Customer says this just happened with latest update and I see it here as well: http://demo.churchthemes.net/uplifted/

Customer threads:  
https://secure.helpscout.net/conversation/86808982/4289/ 
https://secure.helpscout.net/conversation/86261339/4263/
https://secure.helpscout.net/conversation/81823265/3960/

**Comment by angela-crist** [comment]
The customer also brought to our attention that the mobile menu doesn't work either:
![slack for ios upload 1](https://cloud.githubusercontent.com/assets/7047954/7381220/4db540be-edcf-11e4-9f08-e7f73493d2b4.png)

**Comment by chriswallace** [comment]
Should be fixed and deployed to ChurchThemes customers.

**Comment by angela-crist** [comment]
I informed all of the customers.
