### ISSUE TITLE
Customer issue on mobile since last update. Clicking on menu creates a white space at the top

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#117]
I asked the customer to disable plugins to see if one is causing this.  He said he did that prior to the update (and will try again) but this didn't happen prior to the update.

I can't reproduce this in the demo (demo.churchthemes.net) so I'm not sure what else to try.  

Here's what it looks like:
http://lift.d.pr/ceHY/1KDjpzlD

http://aftonwc.com
Awaiting for admin access - Customer thread:  https://secure.helpscout.net/conversation/86808982/4289/

**Comment by angela-crist** [comment]
Here's the admin credentials: 
temp_CTadmin
P@55word

http://aftonwc.com

**Comment by garand** [comment]
It's because of the `fixie` class on the body.

**Comment by angela-crist** [comment]
Thanks @garand Can you tell me how to fix this?

**Comment by angela-crist** [comment]
It's not doing this in the demo, so is this something that the customer added?

**Comment by garand** [comment]
Nope. Have them update to 1.2.5 and see if that fixes it.

**Comment by angela-crist** [comment]
Thanks @garand I updated the customer.  I will close this once confirmed it is fixed.

**Comment by angela-crist** [comment]
Closing out and will reopen if customer issue is still present.
