### ISSUE TITLE
Customer issue: Can't customize site they receive an error

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#119]
When going to Appearance > Customize they get:
http://lift.d.pr/6TpI/2iCVMAvO

http://www.firstassemblyfranklin.org/wp-admin/
user: monicacollier76@gmail.com
pass: 1eiffelTower96!

Her PHP version is 5.4
She bought through ThemeForest
Her license key activation button is also not showing #118  this does not allow her to have the most current version of Uplifted.

We deactivated the plugins and nothing seemed to be causing this. 

Please help, this customer is frustrated and he not complete by the end of the week she is going to another theme. 

Customer thread:  https://secure.helpscout.net/conversation/91670441/4520/

@garand @chriswallace Any ideas?

**Comment by chriswallace** [comment]
I'm looking at this now, not sure what the issues is here.

**Comment by angela-crist** [comment]
Thanks Chris!

**Comment by chriswallace** [comment]
OK, this has been fixed and pushed to ChurchThemes. [This ZIP file](http://lift.d.pr/18q1h) contains the fixed version of Uplifted, you may provide it to verified customers. Also, ensure that each customer is getting a license key from our site and NOT using their ThemeForest key.

**Comment by chriswallace** [comment]
Actually, I didn't look at the Customizer issue.

**Comment by chriswallace** [comment]
All I did was fix the license key issue. Not sure what is wrong with their customizer. Ours works just fine on my local so I don't really know what the problem might be there. Probably a cheap web host issue. I would advise them to switch to our hosting when it becomes available next week.

**Comment by angela-crist** [comment]
She already checked that she has the current PHP version.  Would their still be a problem with their host?

**Comment by angela-crist** [comment]
Updated the customer with the new zip flle and ensured she got her license key from us and then to reach out to her hosting provider:  https://secure.helpscout.net/conversation/91670441/4520/

**Comment by angela-crist** [comment]
@chriswallace Let me know if I need to do anything else for this customer or if this can be closed.

**Comment by angela-crist** [comment]
I will close this issue for now and reopen if the customer comes back to us.
