### ISSUE TITLE
Customer receiving Parse Error 

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#120]
http://lift.d.pr/1aP9S/4By58AhW

"It looks like I only get the error when I try to have CT People in the Sidebar Widget." - From Customer (https://secure.helpscout.net/conversation/91112155/4517/)

He has a PHP version of 5.3. http://take.ms/wn6TG

Customer site:  http://www.inlandbaptist.com/sermons/

Any ideas?

**Comment by garand** [comment]
I believe this is because PHP 5.3 handles array syntax differently than PHP 5.4. Looks like the code is in our theme, not in the plugin, so it should be an easy fix. I'll deploy something a little later today.

**Comment by angela-crist** [comment]
oh ok, just to clarify, I don't need to tell the customer to update their PHP?

**Comment by angela-crist** [comment]
@garand Any updates for this?  Also just to confirm I don't need to tell the customer to upgrade PHP, correct?

**Comment by angela-crist** [comment]
@garand When you are back to the office, please update me.

**Comment by garand** [comment]
Correct. My goal is to have this fixed by noon.

**Comment by garand** [comment]
@angela-crist This has been updated. Have the customer update to version 1.2.7.

**Comment by angela-crist** [comment]
Awesome! Thanks! Updating customer now
