### ISSUE TITLE
Customizer color palette is wonky

### ISSUE THREAD

**Issue by michaelbeil** [ChurchThemes-WP/uplifted-theme#121]
Footer menu goes white when switching to custom colors. It seems as though the secondary color is remaining the same as the primary color, of the built in color palettes, or background color of the page. 
![footer1](https://cloud.githubusercontent.com/assets/4752949/8753801/3ddfc8be-2c84-11e5-8fe7-c2c12614cde2.jpg)
![footer2](https://cloud.githubusercontent.com/assets/4752949/8753802/3de17632-2c84-11e5-8dce-1483fdeb2c5d.jpg)

**Comment by angela-crist** [comment]
How's this going?

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/103067536/4829/

**Comment by angela-crist** [comment]
@christianc1 Could you take a look at this I think this customer https://secure.helpscout.net/conversation/118197522/5229/ is also having a similar issue with the colors.

**Comment by christianc1** [comment]
Fixed in 1.3.4

**Comment by angela-crist** [comment]
Hey @christianc1 I'm not seeing the secondary color only on the 'give' button.  Do we have the secondary color defined of where it should show?

**Comment by angela-crist** [comment]
Here's a screenshot...ignore the crazy colors http://lift.d.pr/AQSm/2DFLWaEA

**Comment by christianc1** [comment]
To put it as simply as I can, the user selects the background color of their choice and the theme generates stylesheets selecting colors that contrast to the background color.  For example, if the user selects a dark color as the background, the stylesheet automatically selects white text for easy contrast. The original issue here is that when a user selected a light gray color, the theme generated a white text color which was difficult to read.  If we want to explicitly set certain font colors to match explicitly set colors from the customizer, that's a separate issue.

**Comment by angela-crist** [comment]
Oh I get that. My bad. Sounds like I just need to open a new ticket.  I'm trying to understand where I will see the secondary color. http://lift.d.pr/17wNi/GeDAgsTI

**Comment by christianc1** [comment]
https://github.com/ChurchThemes-WP/uplifted-theme/blob/3b2004c12a8d579460996cef1524171780da2d0a/assets/sass/colors.scss

cmd+f "$secondary-color"

:)

**Comment by christianc1** [comment]
Okay according to the CSS, the following elements use the secondary color:

- Giving widget button
- Comment respond required contextual help
- Modern Tribe Events plugin button hover state
- MT Events calendar links, tooltips, and something to do with the slider.
- Slide text
- Pagination current page link
- Sermon meta hover state
- Sermon sidebar h3
- Navigation links that are styled as buttons
- Churchthemes Content Category Widget list items
- Recent comment widget links
