### ISSUE TITLE
MP Stacks no longer showing within a page 

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#126]
When activating MP Stacks you no longer see it as an option in pages as we once did. http://lift.d.pr/1ebVe/w5v8EfwT

This does not show within the demo either: http://demo.churchthemes.net/uplifted/

MP Stacks, like live composer is packaged with Uplifted and should be activated upon install of the theme. Or at least installed. 

Please review.

To reproduce:
1. Go to the demo site and create a page.
2. See there is no longer an MP Stacks button above the toolbar

This is happening with new installs as well.

Let me know if you know if you have questions.

**Comment by christianc1** [comment]
Okay, from some discovery, I've discovered that at some point, likely around the version installed on the demo site (v 1.0.1.0) the MP Stacks plugin changed how they put their plugin together.  It now requires the MP Core plugin and the MP Stacks plugin.  On anyone affected by this, they should see a notification on the top of the plugins page alerting them that there is a plugin that is required to be installed.  Clicking the "Install" button on that message should resolve the problem for them.  However, we need to discuss this more Angela, let me know when you have time.

**Comment by angela-crist** [comment]
**Christian** - 
Options:
- Install core and not worry that they don't have the latest version
- Or email the customers with directions how to update their plugins Stacks and Core

**Chris** -
- We are steering people towards people towards Beaver Builder  
- Update the bundle that comes with Uplifted 
- Set a custom package url for the plugin - sets a version of the MP Stacks to the right directory 
- Come up with a canned response, we no longer offer MP Stacks we recommend Beaver Builder 

**Outcome** - Update bundle without MP Stacks and update customers

**Comment by angela-crist** [comment]
The bundle was updated no longer including MP Stacks.  Any customer having issues, just needs to click the "Install Required Plugins" button. - From @christianc1
