### ISSUE TITLE
Update oEmbed code 

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#127]
Issue with oEmbeds. The jQuery library we're using is way outdated, here is the best fork : https://github.com/nfl/jquery-oembed-all or as perhaps a better alternative https://github.com/embedly/embedly-jquery

This is going to take an hour or two to complete, 

Due to embed.ly now requiring a key to access their api

**Comment by angela-crist** [comment]
@chriswallace @garand Is this something you can look into?

**Comment by garand** [comment]
I thought that WordPress core handles oEmbeds?

**Comment by christianc1** [comment]
Only inside the editor.  The theme uses https://github.com/ChurchThemes-WP/uplifted-theme/blob/master/assets/js/jquery.oembed.js to handle embeds on things like the front page, or other non-core areas.

**Comment by angela-crist** [comment]
@garand do you need anything for this?  Let me know what the next step is.  Could we have this complete by Thursday?

**Comment by garand** [comment]
Probably not, I'm not too familiar with this and it seems like it will be more than just dropping in a new framework.

**Comment by angela-crist** [comment]
ok @christianc1 Could you chime in here with the next steps to save Anthony some discovery time.

**Comment by angela-crist** [comment]
@christianc1 Just wanted to follow up if you had a minute to provide some guidance to Anthony to save him time.

**Comment by angela-crist** [comment]
Info from customer: I was trying to add embed video in the homepage slider but the video is not playing and there's an error message in the console. 

Image of error: https://d33v4339jhl8k0.cloudfront.net/inline/6379/c0e89993cd9cb146f0f3135a89909f4b72634c7a/75019b8253ecbc8d8e9f7d39d028a02d4f43faba/Screen-Shot-2015-12-23-at-5-26-58-PM.png

http://sflovechurch.com/
username: mason
password: aSqx%FyIvJf859Mi2&0XW5LX

@christianc1 Any advice for @garand to get this completed?

**Comment by angela-crist** [comment]
This customer ended up creating a child theme and doing his own video for the site.
 
@chriswallace Should we still update the oEmbed code? If not, I will close this issue. 

> Issue with oEmbeds. The jQuery library we're using is way outdated, here is the best fork : https://github.com/nfl/jquery-oembed-all or as perhaps a better alternative https://github.com/embedly/embedly-jquery
This is going to take an hour or two to complete,
Due to embed.ly now requiring a key to access their api

**Comment by angela-crist** [comment]
Got another customer reporting that they cannot create a slide with a youtube video link.  This customer has the most recent version of the theme and purchased it 1/22/16 Here's the customer thread in HelpScout: https://secure.helpscout.net/conversation/168572552/5935/?folderId=272858

I think this would be the same issue and the oEmbed needs updated.  Please let me know if this is the case, what our next step is and an ETA. Then I will update the customer.

**Comment by angela-crist** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pPxBFYeO&#x2F;3-uplifted-slide-with-video-link-does-not-allow-you-to-click-play"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Uplifted: Slide with video link does not allow you to click play</a>

**Comment by angela-crist** [comment]
### User has
- [x] Self-hosted with Valid License Key
- [ ] WordPress.com 
- Version of the theme: **Most recent - 1.3.45 / purchased 1/22/16**
- URL:  http://netchurch.cc
- Admin Access: 
username: support
password: j)82e)Dmt(yi74S^YnIYlu&a

### Trouble-shooting thus far
@christianc1 pushed a branch to uplifted re: oembed @garand, "it’s to get you started. It’s been a while but this was originally my issue right before we got busy, and I got pulled off support. I remember doing some work toward a fix, and when I load up my local, it looks like the embeds are working but the styling is wrong because probably different selectors. Good luck!" (convo started here: https://liftux.slack.com/archives/churchthemes/p1456449067000032)

### Issue Type
- [x] Bug 
- [ ] Enhancement
​

### Expected Behavior
Add a youtube link for a slide, click on play button, it plays
​
### Actual Behavior
Add the slider, click save, on homepage you can't click on the play button
​
### Steps to Reproduce
  1. Add a slide to the slider 
  2. Add a video url to the slide http://lift.d.pr/O888/4GHes9uD
  3. Click Save
  4. Go to homepage and go to that slider
  5. Can't click on play button / doesn't play 

This is also apparent on our demo: http://demo.churchthemes.net/uplifted/
​
@garand @christianc1 @chriswallace Do any of you have time to complete this this week? This current customer first came to us 2/6/16.

**Comment by garand** [comment]
This is fixed.

Awaiting @angela-crist to test the two zip's of the theme I uploaded to Slack.

**Comment by angela-crist** [comment]
@garand Finally got a second to test... both version UpThemes and ChurchThemes worked great! Video plays now.  Let me know when I can update the customers.

Thank you!

**Comment by angela-crist** [comment]
Anthony added the latest update and I updated customer

**Comment by angela-crist** [comment]
The video play button on the slide is not working again. Any ideas? @garand @christianc1 

You can see it on our demo and customers sites. Click to the video slider on our demo: http://demo.churchthemes.net/uplifted/ and click play...nothing..

Let me know what the next steps are. Thanks!

**Comment by christianc1** [comment]
http://docs.embed.ly/docs/authentication

User may have to take additional steps to enable embedding.  We may have to come up with a different solution to get this working properly.

**Comment by angela-crist** [comment]
Hmmm it must be that not many users use the video option.  I have never had a user have to do this. Looking at the instructions not sure if they will understand what to do. Wondering what we should advise someone that is a newbie to WordPress.

**Comment by angela-crist** [comment]
Realized the customer most have had a previous version of the theme as it works in 1.3.6
