### ISSUE TITLE
Slider images are blurry only on iPad view 

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#130]
### User has
- [x] Self-hosted with Valid License Key
- [ ] WordPress.com 
- Version of the theme: 1.3.45
- URL:  http://www.kwwem.com/ and our demo: http://demo.churchthemes.net/uplifted/
- Admin Access: 
User: katepa
Pass: ovZ48VY92muUnTg
- Link to HelpScout issue: https://secure.helpscout.net/conversation/156978294/5793/?folderId=272853

### Issue Type
- [x] Bug 
- [ ] Enhancement
​

### Expected Behavior
Images not to be blurry
​

### Actual Behavior
Viewing the slider on iPads, the images look blurry.  On mobile and desktop these images look fine.  This is happening on both customer site and our demo: http://demo.churchthemes.net/uplifted/
​
### Steps to Reproduce
  1. Go to a Uplifted site on iPad
  2. See images are blurry

@garand @chriswallace @christianc1 Let me know if any of you have time to complete this, this week. This issue we have talked about in slack and trello.  It came to us 1/31.

**Comment by angela-crist** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jzsB9xyX&#x2F;2-uplifted-3-questions-locations-slider-images-blurry-on-ipad-alignment-issue-within-sermons-page"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Uplifted: 3 questions - Locations, Slider images blurry on iPad, alignment issue within sermons page</a>

**Comment by angela-crist** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;CgeBgWhu&#x2F;15-slider-images-blurry-on-ipad"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Slider images blurry on iPad</a>

**Comment by angela-crist** [comment]
![img_0839](https://cloud.githubusercontent.com/assets/7047954/13990030/29738576-f0e9-11e5-945f-0182e95d7a5d.PNG)
![img_0840](https://cloud.githubusercontent.com/assets/7047954/13990036/2dc3f62e-f0e9-11e5-8d70-3331f10e85f0.PNG)

I don't currently have the latest iOS and I saw this in both Safari and Chrome. Checking on another iPad as well and I can reach out to the customer to see if she is still experience as I am.

**Comment by garand** [comment]
@angela-crist Can we close this out now?

**Comment by angela-crist** [comment]
Thanks @garand 

This was fixed by an update in the iOS. I will reopen if the customer has an outstanding issue with this.
