### ISSUE TITLE
Upgrading to the latest version of WordPress no longer displays the slider

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#132]
I have had several customers that upgraded to the latest version of WordPress and as soon as they did that the homepage slider was no longer there. 

The slider is still on our demos however I do not believe we have the latest version of WordPress. 

We have many customers wanting this resolved as soon as possible is this something we can squeeze in and complete by Wednesday? @christianc1

**Comment by angela-crist** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9fD7EjBO&#x2F;19-uplifted-slider-no-longer-showing"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Uplifted - slider no longer showing</a>

**Comment by angela-crist** [comment]
Hmmm I just had a customer say once they updated all of their plugins the slider worked again.  I will update you if this still needs to be looked into. Thanks!

**Comment by christianc1** [comment]
Okay let me know if I need to do anything here.

**Comment by angela-crist** [comment]
Thank you Christian. I will close or update this once I hear back from all customers that had this issue.
