### ISSUE TITLE
Customer issue has current version of Uplifted but still has the nag message to update

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#134]
The reminder to update Uplifted still shows even though they have the latest version. Anyway to remove? http://lift.d.pr/vGbl/3UA0lD7z

http://kalamazoofmc.org/
upthemes and the pwd is gDj)hjHt3foG*kWelUY5pQ7e

What's new page: http://lift.d.pr/8IsP/MvBmAgHH

**Comment by garand** [comment]
Log in and click "Check out what's new.", then post a screenshot of that panel.

**Comment by angela-crist** [comment]
Closing this out. Haven't heard back from the customer.
