### ISSUE TITLE
Uplifted integration of The Events Calendar 4.1 with attendee info

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#135]
This Uplifted customer is using the new The Events Calendar feature: https://theeventscalendar.com/knowledgebase/collecting-attendee-information/

When a user increases the ticket quantity, additional fields are suppose to show...here's a page where it's not working: http://www.jitterbugs.org/event/rhythm-weekend-tap-dance-festival/

Can you take a look to see if we there's a conflict with our theme or a simple solution. 
Since we marketed The Events Calendar with Uplifted in the beginning I would like for him to be able to use it but I don't want to do anything that's out of our support scope. Let me know your thoughts.

Customer thread: https://secure.helpscout.net/conversation/187894540/6090/?folderId=190432

**Comment by christianc1** [comment]
@angela-crist: There is a javascript error in the console thrown by The Events Calendar code.  Have them debug the error first and have customer reopen if they say it's related to the theme. http://lift.d.pr/1bzKP/3PQ38IOo
