### ISSUE TITLE
Do some exploratory work on some companion plugins.

### ISSUE THREAD

**Issue by chriswallace** [ChurchThemes-WP/uplifted-theme#21]
@inspectorfegter and I discussed a few feature plugins that would be immensely helpful for getting churches set up on the Uplifted theme and WordPress in general.

* Fellowship One integration plugin - could do SSO, online giving, some limited member management via WordPress admin.
* Small Groups post type - Would add a small groups admin to theme, similar to sermons, people, events, locations.
* AppPresser extension with push notification capabilities and mobile app for church members.
* Planning Center integration - An app for music in churches, would be interesting to maybe list schedules, music, teams, etc. in their WordPress site somewhere. Not sure how this would interact with theme or how useful it might be with what their API is capable of.

**Comment by angela-crist** [comment]
@chriswallace Do we still need this open?

**Comment by garand** [comment]
I would say close out and if we want to pursue these things, roll them into Faithmade.
