### ISSUE TITLE
The Custom Color Schemer

### ISSUE THREAD

**Issue by calebsylvest** [ChurchThemes-WP/uplifted-theme#83]
I've had some thoughts on the Custom Color Schemer and how the options function. I knew it was never the easiest to figure out and use, and I've talked with a number of customers who are confused how to make it work. What I am suggesting isn't *perfect*, but I think is a good step in the right direction.

Problem:
-The custom color scheme functionality is kind of hidden.
-The build your own color scheme option is *very* hidden, confusing, and requires several clicks to activate.

Solution:
Reduce complexity.
1. Get rid of the first step of "Enable Custom Styles". (Which already is confusing because we are talking about Colors, not Styles). Show the full list of pre-defined color schemes from the get-go, with the active scheme highlighted.
2. Have a checkbox to turn on Custom Color Scheme.
3. When Custom Color Scheme is activated the pre-defined schemes are hidden and Color Picker boxer for custom scheme are presented.

I don't think the checkbox is *perfect*, but definitely makes more sense and reduces confusion.

![uplifted-color-schemer](https://cloud.githubusercontent.com/assets/4457883/5322671/717a3076-7c8d-11e4-9909-e014f9c456a6.png)

**Comment by angela-crist** [comment]
@garand @chriswallace Can we close this out or do you want to still examine changing this up?

**Comment by garand** [comment]
Close out, we will roll future color modifications into [UpThemes/Colorcase](https://github.com/UpThemes/Colorcase).
