### ISSUE TITLE
Look at podcasting enhancements

### ISSUE THREAD

**Issue by angela-crist** [ChurchThemes-WP/uplifted-theme#91]
This was brought to us by a customer who had Antioch previously. He feels Uplifted is lacking in comparison and I agree.  Here's the ticket you responded to:  https://secure.helpscout.net/conversation/67489312/3160/

**Comment by angela-crist** [comment]
Do we want to make any changes to the podcast for Uplifted or close this out?

**Comment by garand** [comment]
I would say close this out and we'll make future podcasting enhancements to Faithmade. Reopen if you feel otherwise.
